### ISSUE TITLE
Meetups not shown

### ISSUE THREAD

**Issue by rbowen** [OSAS/rh-events#125]
I've added a bunch of RDO meetups (an event series), and they don't display on community.redhat.com or on beta.rdoproject.org/events/

**Comment by garrett** [comment]
Have you rebuilt either site with the new commits?

Other sites do not auto-rebuild because an external repo changes, and it would be tricky to do so. AFAIK, @mscherer has some code to rebuild on a time delay with new events, but that might be a bug in each site then — it definitely has nothing to do with rh-events, unless the events do not validate (and then CI would fail — this is why it's a good idea to submit new events through pull requests, _or_ use `./validate.rb` from the command line otherwise).

**Comment by garrett** [comment]
(In other words, `rh-events` is basically just a repo of data. It's up to the sites to do something with the data here.)

**Comment by garrett** [comment]
The community website is on our internal GitLab instance. If we fix it for RDO, then we can (and should) fix it for the community site too.

**Comment by garrett** [comment]
Added the issue for the community site on our internal GitLab instance, too: http://gitlab.osas.lab.eng.rdu2.redhat.com/garrett/community-middleman/issues/46

**Comment by mscherer** [comment]
So yes, by default, I have "rebuild every 6h" to cope with that. That's rebuild once there is a commit on the main repository, and -h to cope with the sub module. I could switch on watching 2 repo, but that's a bit more work and I can't devote time on it for now.

**Comment by garrett** [comment]
The issue was that the events did not have ending times, so each talk in the series lasted to infinity. (...and beyond?)

I've added code to handle an errant oversight like this, so that if there is no end time for a talk (specifically a talk), then it would last for an hour, which I think is a reasonable default.

**Comment by garrett** [comment]
(That code I'm referring to is in the RDO website only at the moment. I did some quickly write and apply some hotfix code to skip over faulty talks that's on both RDO and the Community site, however, as a result of this issue.)
